### ISSUE TITLE
[BUG] Readme in setup dir does not install latest version of workoutizer

### ISSUE THREAD

**Issue by gotiniens** [fgebhart/workoutizer#159]
**Describe the bug**
The readme in the setup dir says you should use Raspian 10 (buster). Raspian 10 comes with python3.7.3 installed. And a higher version is not in the repositories.

Since version 0.7.1 and later workoutizer requires python version >=3.8, So 0.7.0 will be the newest version installed

**To Reproduce**
1. Install a clean Raspian on an supported raspberry pi
2. run `pip install -vvv workoutizer`
3. Assert that the version being installed is 0.7.0
```  Link requires a different Python (3.7.3 not in: '>=3.8'): https://files.pythonhosted.org/packages/72/a2/ab6355491543ac1254dc3a93061a4c5bae70a100c2245084d18fbcb1bbb1/workoutizer-0.7.1-py3-none-any.whl#sha256=188e0c97d243a5c64be15309f033d529d49831bc1d481a78dab3ce35c56ebbe5 (from https://pypi.org/simple/workoutizer/) (requires-python:>=3.8)```

**Expected behavior**
Install latest version of workoutizer

**Additional context**
You can probably install an newer version of python via other repositories.

**Comment by fgebhart** [comment]
Good catch!

I have to admit that the `setup/Readme.md` was not well maintained in the past. Actually, I would prefer to host a proper static docs page (similar to what I build for [sportgems](https://fgebhart.github.io/sportgems/)) including a dedicated section on how to install workoutizer on a Raspberry Pi. It has been on my list for too long..

You are totally right, python3.7 is the latest version shipped with buster and workoutizer support Python3.8 and 3.9 only since quite a while already. We could, however, try one of the following to resolve this:

1. Add an description of how to install python3.8 on your raspberry pi to the readme. It is likely that future debian versions would ship python3.8 anyway. However, this would result in additional effort for the users who want to give workoutizer a try on their RPIs.
2. Officially support python3.7 with workoutizer. Currently I cannot think of any features within the code base which are >=Python3.8 only. Thus, I would expect the efforts for this option to boil down to adding python 3.7 to the [CI pipeline matrix](https://github.com/fgebhart/workoutizer/blob/main/.github/workflows/python-tests.yml#L34). But I might of course be overlooking something. Supporting multiple python version would lead to higher maintenance efforts but opposed to the above version would improve the UX.

I tend to prefer option 1, since I'm anyway having too less time for proper maintenance. What do you think?

**Comment by gotiniens** [comment]
Personal projects are always a bit under documented, because you now what changes you made in the past :) Also it is a relativly new project (at least on github) which does not help in this regard either.

regarding your solutions:

1. This mostly depends on the ways available to install python3.8. Adding an repo or compiling python from source are completley different things. Compiling could be too much effort for beginners, which would then shy away from the project. 
2. From your wording of certain things and some features it looks te me the project is mostly aimed at running on an Raspberry Pi, with that in mind I would say aim the project on current version of Raspbian.

That said, the next release of Debian goes in Full Freeze on the 17th of July, and includes Python3.9. A release will not be far away I think. And Raspbian not long after that. If you target python3.9 you have a bit more complicated install now, but have no work to migrate to the new python version later.

**Comment by fgebhart** [comment]
You are right. Workoutizer is kind of aimed at running on a Raspberry Pi while at the same time I would like to lower the barrier for getting started with it.

Created #162 for this purpose.

**Comment by gotiniens** [comment]
With the new 0.20.0 release which fixed #162 for me, I still had some improvements for the Readme. See #166

**Comment by gotiniens** [comment]
As mentioned, the 0.20.0 release fixed this issue for me, and with the rest of the Readme suggestions merged I have no further remarks.
