### ISSUE TITLE
Trouble getting workoutizer to work

### ISSUE THREAD

**Issue by bintzandt** [fgebhart/workoutizer#90]
Hey! :wave: 

Let me start by saying that I love the looks of your project! It looks really great and I would love to get this up-and-running for my device.

However, the setup for this project does not seem to be as simple as the README.md says. In fact, I have not been able to get it running using the package provided in pip.

I cloned the repo to investigate the problems and it seems to roughly boil down to these two:
1) My Garmin device (a Garmin Venu SQ) does not store the activities inside the folder that is hardcoded in the application (`/Primary/GARMIN/Activity`). Instead it is stored at `/Garmin/Activity`. It would be nice if that value is configurable.
2) Automatic imports do not seem to be working. Even after changing the path above to be correct, the codebase seems to make assumptions about the filesystem of the device. In my case, the Garmin watch gets automatically mounted at `/run/media/bintzandt/GARMIN`. This would make the mounting step in `mount-device` unnecessary.

I managed to get it somewhat working by changing the following things:
1) The path at which the activity folder is stored
2) Creating a new route for copying the Fit files from my device. I created an `/update/` route which does the same as `mount-device` except for mounting the device :stuck_out_tongue:.

After that, I got workoutizer to load the files. However, error did still occur:
1) The `m_per_s_to_km_per_h` filter crashed because `m_per_s` was not defined in the file, causing `float()` to run on `NoneType`.

I have added an additional check to make sure that that code only runs when `m_per_s` is defined.

These changes allow me to run `workoutizer` locally. Since I only have one workout file, I am unsure if these fixes are very stable.

Besides that, I am not a Python developer so I have probably created a lot of other error :sweat_smile: 

Anyways, I just wanted to let you know what is up. Hopefully, you (we?) will be able to resolve the issues.

Again: thanks a lot for creating this! I look forward to use it.

**Comment by bintzandt** [comment]
Update: I have tried to install `workoutizer` in my Raspberry Pi because that seems like a great solution to be able to access the web interface.

While mounting the device I get the following error:
```
gio: /dev/bus/usb/001/005: No volume for device file
```

**Comment by fgebhart** [comment]
Hey there 👋 
thanks for reaching out and sharing your feedback - I'm happy to help!

As you can image I only tested the code base to be working with the garmin device I'm currently using in combination with running it on a Raspberry Pi. Operating workoutizer on a different OS and with a different Garmin device seems likely to introduce new challenges. Solvable challenges I guess 😃 

I think it would be great if we could go through all the mentioned issues step by step and eventually put `Garmin Venu SQ` on a list of supported devices. For that I would propose to create separate issues in order to be able to track the different problems.

So far I can see the following todos:
1. make path to activities on garmin device configurable
2. prevent `m_per_s_to_km_per_h` filter from crashing
3. solve issue of unneeded mounting in case device already gets mounted automatically
4. solve issue of mounting Garmin Venu SQ on Raspberry Pi

My first impression is: 1 should be pretty easy - I will start by creating a ticket for it. 2 should also be easy, but I could need some more infos. It would be great if you could create a ticket for 2. If you don't mind sharing your `.fit` file which caused that issue, that would speed up the debugging and development a lot - if not no problem, I might be able to generate the situation with dummy test data. For 3. I might need to think about this a bit to figure out what a good design would be. And 4. might be tricky since I cannot debug it 🤷 I assume you already went through [this guide](https://github.com/fgebhart/workoutizer/tree/master/setup)? If yes, I also have [this unstructured list of handy commands for debugging mounting on RPI](https://github.com/fgebhart/workoutizer/blob/master/setup/other/debugging.md) laying around, maybe it is helpful to you? Also, feel free to open a dedicated issue for 4. with more details.

I guess that is already enough to work on for the beginning. Let me know if I missed something or misunderstood something. 

Awesome, that you even started to fix the issues yourself. I myself would probably already have given up after seeing all these issues 😆

**Comment by fgebhart** [comment]
@bintzandt I opened #92 for #91 (1 in above list). Could you maybe double check if that is what you were looking for? Maybe even checking out that branch locally and giving it a try? (Note: Don't know how familiar you are using Django, but you would also need to run
```
wkz manage migrate
```
after switching to that branch, in order add the new settings column to the db.

**Comment by bintzandt** [comment]
Yes! That is exactly what I was looking for. I manually changed the path in the python file, but #92 seems like a much better solution.

> Note: Don't know how familiar you are using Django

I'm not familiar with Django at all. But I would like to learn in order to be able to help you out a little :)

> If you don't mind sharing your `.fit` file which caused that issue, that would speed up the debugging and development a lot

I don't mind sharing it _with you_ but I am not too happy to post it somewhere publicly (like GitHub). If you have somewhere I can reach you, I can send you the file :)

I'll have a look into the other issues that I raised to see if I can think of a way to fix them / create a issue for them with more details.

Thanks for your time and quick response!

**Comment by fgebhart** [comment]
Great. Thanks for the feedback. I have merged the PR. Will probably soon do another release including this change.

> I don't mind sharing it with you but I am not too happy to post it somewhere publicly (like GitHub). If you have somewhere I can reach you, I can send you the file :)

I've send you an email to the address on your website 😉  I guess that way should work.

**Comment by bintzandt** [comment]
> I've send you an email to the address on your website :wink: I guess that way should work.

I have seen your email but I have been busy with other things the last few days... I will try to send the FIT file today or tomorrow :)

**Comment by fgebhart** [comment]
Thanks for the file @bintzandt, was able to test it and created #95 which corresponds to 2 in the above list. I guess this bug is fairly easy to solve.

If you would like to get involved in fixing this and raising a PR I would be happy to provide some context and guidance. Just reply to to #95 if so. If not, no problem, I can take care of it.

**Comment by fgebhart** [comment]
Nevermind, I guess I was too quick.. 😄 

Just merged the fix for #95. With this Point 1. and 2. from above list should be fixed. You should be able to import your activity now (still by placing it into the trace dir manually - I'm still working on #94 to enable auto importing in case of auto mounted devices).

@bintzandt would be great if you could verify that my changes solve the issues 1. and 2.

**Comment by fgebhart** [comment]
@bintzandt I managed to rework the mounting and file importing workflow. This fixes (at least in my eyes) point 3.

It now works like this:
* a watchdog is in place monitoring whether the device is present in the directory specified in `settings.path_to_trace_dir`
* there is no longer a need to configure the path to the activity dir on the device itself. Workoutizer now has a auto detection mechanism which finds the dir in case it is called "Activity" (which is currently the case for all devices I am aware of). This makes the above point 1. obsolete, which got removed again.
* Once the device is present in this dir, new activity fit files are copied into the trace dir
* A second watchdog is monitoring the trace dir, and triggers file importing whenever a new file is added to the trace dir
* independent of this, the `mount-device` endpoint does now only mount the device and longer triggers the copy. Copying is done with the above described.

Have a look at [v0.14.0[(https://github.com/fgebhart/workoutizer/blob/master/CHANGELOG.md#workoutizer-0140-2021-03-15) and let me know if this approach works for you.

**Comment by bintzandt** [comment]
Hi @fgebhart!

Thank you for your hard work. I have just tried the new release (0.14.0).

I can confirm that #95 is indeed fixed :+1: 

However, the filewatcher does not seem to automatically copy files from my Garmin device to the `tracks` directory. 

I had a quick look at the code and you have added this variable `self.sub_dir_for_garmin_files = "garmin"` (it was already present as a constant, I know...).

At least on my device the sub-directory in which the `Activity` folder resides is called `GARMIN`. I'm not sure whether that is related?

**Comment by fgebhart** [comment]
The variable `self.sub_dir_for_garmin_files = "garmin"` is used to create a subfolder inside the `tracks` directory where the files are copied to (in the target directory), when copying from your device. I initially introduced this to separate garmin activity files from other activity files, since it is still possible to also add other file (e.g. `gpx`) files manually (or via an additional, external automated flow) to the tracks dir and workoutizer would automatically parse them. So this should not be the issue.

Could you provide the complete system path in which your activities `fit` files are stored on your device?
On my Raspberry Pi this is at `/run/user/1000/gvfs/mtp\:host\=091e_4b48_0000c4fa0516/Primary/GARMIN/Activity/<activities>.fit`. Once the device is unmounted I'm left with `/run/user/1000/gvfs`, which is the path I have configured in `settings.path_to_trace_dir`. I assume this is similar to your setup?

Currently, there is a hard-coded depth of 4 in the "activity folder autodetection mechanism" in place:
https://github.com/fgebhart/workoutizer/blob/master/wizer/file_helper/fit_collector.py#L34
In case the activity folder on your device is nested even deeper inside your device, workoutizer won't find it.

Additionally, you could set the logging to `DEBUG` by
```
export WKZ_LOG_LEVEL="DEBUG"
```
and paste the entire output here, when running `wkz run` while your device is mounted. This could provide additional insights.

Hope that helps.

**Comment by bintzandt** [comment]
> Could you provide the complete system path in which your activities `fit` files are stored on your device?

While I was doing this, I noticed that you mentioned that you use `/run/user/1000/gvfs` as your `settings.path_to_garmin_device`.

My complete path is `/run/media/bintzandt/GARMIN/GARMIN/Activity/*.fit` so I entered `/run/media/bintzandt/GARMIN` as the device path. This did not work.

However, when I entered `/run/media/bintzandt` (without any GARMIN specifics like in your example) it does pick up the activities :)

So I guess that the issue is solved? :smile:

**Comment by fgebhart** [comment]
Awesome! Glad to hear it works now 🎉 

And yes, let's consider this issue solved. Always feel free to open a new issue in case of any problems. This holds true for point 4 of the above list. In case you want to try running workoutizer on a RPI.

Also, if you think the Readme could be enhanced in a way that future users won't need to go through the same problems like you did, feedback and PRs are highly appreciated :) 

Furthermore, if you should have any ideas on how to improve workoutizer, add new features or rework the frontend, I'm open for suggestions. Why not use the [Discussion Tab](https://github.com/fgebhart/workoutizer/discussions)? I'm continuously adding new features, which I think would be nice to have, but maybe I'm missing something that would be even more valuable...

Lastly, enjoy 😄
